server {
    listen 80 default_server;
    server_name
        pokechess.local
        www.pokechess.local
        app.local
        api.pokechess.local
        api.app.local
        db.pokechess.local
        db.app.local;

    return 301 https://$host$request_uri;
}
