server {
    listen 443 ssl;
    http2 on;
    server_name api.pokechess.local api.app.local;

    ssl_certificate     /nginx/ssl/pokechess.crt;
    ssl_certificate_key /nginx/ssl/pokechess.key;
    include /nginx/ssl/ssl-params.conf;

    root /var/www/backend/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_read_timeout 300;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
